### ISSUE TITLE
Bright Idea not opening using default preset

### ISSUE THREAD

**Issue by technochitlin** [Miff-Real/DanTModules-Manual#21]
Header says it, mostly. Loading the preset after the patch is loaded works fine, but the module ignores the default preset.

**Comment by Miff-Real** [comment]
Sorry, I need a bit more information to understand the issue.

Do you mean that the module is not loading with the parameter values you expect? Could you please describe the situation when this happens, the parameter values that are loaded, and the parameter values you expected?

When you save a `default preset` this is the parameter values that load when you add the module to a patch.

These values do not apply when you load a patch that already has the module added, they only apply when you add the module from the browser.

This is how I test this behaviour:

- Create a patch with a few modules.
- Add the BrightIdea module and set its parameters to what you would like them to be
- Save the default preset
- Remove the BrightIdea module from the patch
- Now change the Rack view settings for room brightness and cable opacity etc
- Add the BrightIdea module back into the patch
- You should see that when you add the module all the parameters are set to what you saved them as in the default patch, and the Rack settings have changed to match

Note also that currently the module does not use the default preset when you `initialize` it, it uses the default values saved by the module.

**Comment by technochitlin** [comment]
OK, now I feel like an idiot, because I cannot reproduce exactly what was happening to me- everything works correctly reproducing your steps. I guess consider it a false alarm until I can get back to you with how it happened.

I hate mysteries like this. I did not imagine it I promise! 😵
________________________________

**Comment by technochitlin** [comment]
OK I can reproduce it. I have Bright Idea as part of my default VCV Rack template; when I load the template Bright Idea is reset to "its" default settings, not my default preset. In every other scenario you described it works perfectly. And yes, when I saved the template, Bright Idea was set to "my" default settings.
________________________________

**Comment by Miff-Real** [comment]
OK, I think your issue is a misunderstanding of the template.

When you select `File > New`, or `Ctrl-N`, this loads the template patch.

This works the same as loading any other patch, the settings of the modules in the patch should be what they were when you saved the patch. Although you are asking for a new patch, this does not act as if all the modules are being freshly added from the browser, it just loads the patch savefile.

If you want the BrightIdea module to have certain settings when you create a new patch, you need to add it to a patch, set the parameters as you want them, then select `File > Overwrite template`.

Then whenever you create a new patch the module should load with those settings, this is not affected by the default preset as far as I understand it.

Does this solve your issue or have I misunderstood?

**Comment by Miff-Real** [comment]
Closing this issue, please reopen if not resolved, or start a discussion here or on the VCV community, thanks.
