### ISSUE TITLE
feature request - snap vcv rack borders to modules

### ISSUE THREAD

**Issue by XtremeSounds** [Miff-Real/DanTModules-Manual#22]
HI I like the Purfenator you did.  I was wondering are you able to make a module that will snap all the vcv rack program's windows borders to snap to the edges of the loaded modules? Sort of creating a box around the modules every time we push a button?

**Comment by Miff-Real** [comment]
Do you mean the edges of the stand alone VCV Rack application, or the in DAW plugin dialog window?

Either way I don't believe that modules have access to the application chrome, so this would need to be a VCV Rack feature request rather than a module feature request.

You can make VCV Rack feature requests either on the Community forum at https://community.vcvrack.com/ or via VCV support https://vcvrack.com/support

**Comment by Miff-Real** [comment]
As an alternative, perhaps this module could be useful? Set the window as you want it, then use this module to jump between different "views" of the patch? https://library.vcvrack.com/Stoermelder-P1/Goto
