### ISSUE TITLE
Feature Request for Bright Idea - configure defaults in module.

### ISSUE THREAD

**Issue by cosmoproductions** [Miff-Real/DanTModules-Manual#5]
Hi Dan.
What do you think of providing a way to set the defaults for opacity, tension, brightness, and bloom in the module itself?  Right now they are hard coded to the VCV Rack defaults, with no way _in the module_ to change the defaults.  Would it be possible for your "Set Defaults" right click menu to have sliders for each parameter, similar to, or exactly the same as, the sliders on VCV's View menu?
Perhaps this is a niche case, but for example, I don't ever want cables with tension less than 100%.  So I figured out I could set the following parameter in the .json to set the default and avoid ever accidentally triggering a switch back to the VCV Rack default of droopy 50% tension cables.
  "defaultBrightIdeaCableTension": 1.0,
As you can see I already have a workaround for the issue I'm concerned about by modifying .json.  Bright Idea is already a fantastic, unique, and super useful module.  So simply offering this suggestion to make a great module even better for others who might not figure out the .json hack.  Thanks for making it.
Cheers!
Gabe

**Comment by Miff-Real** [comment]
Hhmmm, there must be a bug that has been introduced since my last version of the plugin.

Under the `Set Defaults` menu, the items for each parameter are supposed to show the current default value, and if you click on them, they are supposed to save the current module value of that parameter as the default. (So you should be able to set the module cable tension to `1` and then set that as the default value, then in future whenever the module is included, the cable tension is automatically set to `1`.)

I have just tested it though, and it does not seem to be working, I'll need to investigate this and try to figure out a bug fix.

![image](https://user-images.githubusercontent.com/1334054/176782207-a16ad721-f282-4e49-85d8-f0345a9a7158.png)

**Comment by cosmoproductions** [comment]
Oh cool.  After I read the manual and forum thread, I thought you must have that base covered somehow.  It seems you really covered all the use scenarios.   So I wondered if I was doing something wrong when I couldn't find a way to lock in custom defaults.  Thanks for looking into it.

**Comment by Miff-Real** [comment]
I just submitted v2.3.4 of the plugin to VCV which contains the bug fix, hopefully it will be in the library soon.
